//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aadl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aadl.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        public static string lbPhone
        {
            get
            {
                return ResourceManager.GetString("lbPhone", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string lbEmail
        {
            get
            {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string lbCity
        {
            get
            {
                return ResourceManager.GetString("lbCity", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string lbBirthday
        {
            get
            {
                return ResourceManager.GetString("lbBirthday", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to عمليات.
        /// </summary>
        public static string lbActions {
            get {
                return ResourceManager.GetString("lbActions", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        public static string lbCountry
        {
            get
            {
                return ResourceManager.GetString("lbCountry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string lbAdd {
            get {
                return ResourceManager.GetString("lbAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الانشاء من قبل.
        /// </summary>
        public static string lbCreatedByUser {
            get {
                return ResourceManager.GetString("lbCreatedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string lbDelete {
            get {
                return ResourceManager.GetString("lbDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string lbEdit {
            get {
                return ResourceManager.GetString("lbEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الكامل.
        /// </summary>
        public static string lbFullName {
            get {
                return ResourceManager.GetString("lbFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل فعال.
        /// </summary>
        public static string lbIsActive {
            get {
                return ResourceManager.GetString("lbIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string lbNo {
            get {
                return ResourceManager.GetString("lbNo", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to البيانات الشخصية.
        /// </summary>
        public static string lbPersonTitle
        {
            get
            {
                return ResourceManager.GetString("lbPersonTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string lbYes {
            get {
                return ResourceManager.GetString("lbYes", resourceCulture);
            }
        }
    }
}
