//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aadl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResPractitioner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResPractitioner() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aadl.Resources.ResPractitioner", typeof(ResPractitioner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط.
        /// </summary>
        public static string lbAverage {
            get {
                return ResourceManager.GetString("lbAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع القضايا.
        /// </summary>
        public static string lbCasesTypes {
            get {
                return ResourceManager.GetString("lbCasesTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الانشاء من قبل .
        /// </summary>
        public static string lbCreatedByUser{
            get {
                return ResourceManager.GetString("lbCreatedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خبير.
        /// </summary>
        public static string lbExpert {
            get {
                return ResourceManager.GetString("lbExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النموذج.
        /// </summary>
        public static string lbForm1 {
            get {
                return ResourceManager.GetString("lbForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموذج.
        /// </summary>
        public static string lbForm2 {
            get {
                return ResourceManager.GetString("lbForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجانا.
        /// </summary>
        public static string lbFree {
            get {
                return ResourceManager.GetString("lbFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم التعريفي.
        /// </summary>
        public static string lbID {
            get {
                return ResourceManager.GetString("lbID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محكم.
        /// </summary>
        public static string lbJudger {
            get {
                return ResourceManager.GetString("lbJudger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العضوية.
        /// </summary>
        public static string lbMembershipNumber {
            get {
                return ResourceManager.GetString("lbMembershipNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزاول.
        /// </summary>
        public static string lbPractitioner {
            get {
                return ResourceManager.GetString("lbPractitioner", resourceCulture);
            }
        }  
        /// <summary>
        ///   Looks up a localized string similar to المزاولين.
        /// </summary>
        public static string lbPractitioners
        {
            get
            {
                return ResourceManager.GetString("lbPractitioners", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to النظامين.
        /// </summary>
        public static string lbRegulators
        {
            get
            {
                return ResourceManager.GetString("lbRegulators", resourceCulture);
            }
        }    /// <summary>
             ///   Looks up a localized string similar to الشرعيين.
             /// </summary>
        public static string lbSharias
        {
            get
            {
                return ResourceManager.GetString("lbRegulators", resourceCulture);
            }
        } /// <summary>
          ///   Looks up a localized string similar to المحكمين.
          /// </summary>
        public static string lbJudgers
        {
            get
            {
                return ResourceManager.GetString("lbJudgers", resourceCulture);
            }
        }/// <summary>
         ///   Looks up a localized string similar to الخبراء.
         /// </summary>
        public static string lbExperts
        {
            get
            {
                return ResourceManager.GetString("lbExperts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مزاول.
        /// </summary>
        public static string lbPractitioner2 {
            get {
                return ResourceManager.GetString("lbPractitioner2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القضايا.
        /// </summary>
        public static string lbPractitionerCases {
            get {
                return ResourceManager.GetString("lbPractitionerCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المزاول.
        /// </summary>
        public static string lbPractitionerType {
            get {
                return ResourceManager.GetString("lbPractitionerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظامي.
        /// </summary>
        public static string lbRegulator {
            get {
                return ResourceManager.GetString("lbRegulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قضايا نظامي.
        /// </summary>
        public static string lbRegulatorCases {
            get {
                return ResourceManager.GetString("lbRegulatorCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منحة.
        /// </summary>
        public static string lbScholorship {
            get {
                return ResourceManager.GetString("lbScholorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرعي.
        /// </summary>
        public static string lbSharia {
            get {
                return ResourceManager.GetString("lbSharia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قضايا شرعي.
        /// </summary>
        public static string lbShariaCases {
            get {
                return ResourceManager.GetString("lbShariaCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الاجازة الشرعية.
        /// </summary>
        public static string lbShariaLicenseNumber {
            get {
                return ResourceManager.GetString("lbShariaLicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مميز.
        /// </summary>
        public static string lbSpecial {
            get {
                return ResourceManager.GetString("lbSpecial", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to قائمة المزاولين للمهنة.
        /// </summary>
        public static string lbPractitionerListTitle
        {
            get
            {
                return ResourceManager.GetString("lbPractitionerListTitle", resourceCulture);
            }
        }///   Looks up a localized string similar to قائمة النظامين.
         /// </summary>
        public static string lbRegulatorListTitle
        {
            get
            {
                return ResourceManager.GetString("lbRegulatorListTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نوع الاشتراك.
        /// </summary>
        public static string lbSubscriptionType {
            get {
                return ResourceManager.GetString("lbSubscriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طريقة الاشتراك.
        /// </summary>
        public static string lbSubscriptionWay {
            get {
                return ResourceManager.GetString("lbSubscriptionWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دعم خاص.
        /// </summary>
        public static string lbSupport {
            get {
                return ResourceManager.GetString("lbSupport", resourceCulture);
            }
        } /// <summary>
          ///   Looks up a localized string similar to تفاصيل المزاولين.
          /// </summary>
        public static string lbPractitionerDetails
        {
            get
            {
                return ResourceManager.GetString("lbPractitionerDetails", resourceCulture);
            }
        }
    }
}
